---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kubecraft
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubecraft
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubecraft
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubecraft
